seed: 42
run_mode: 'predict'
output_dir: './output'  # 当前不支持自定义修改，请勿修改该默认值
load_checkpoint: ''
src_strategy_path_or_dir: ''
auto_trans_ckpt: False  # If true, auto transform load_checkpoint to load in distributed model
only_save_strategy: False
resume_training: False

# context
context:
  mode: 0 #0--Graph Mode; 1--Pynative Mode
  device_target: "Ascend"
  enable_graph_kernel: False
  graph_kernel_flags: str = "--disable_expand_ops=Softmax,Dropout " \
                              "--enable_parallel_fusion=true --reduce_fuse_depth=8 --enable_auto_tensor_inplace=true"
  max_call_depth: 10000
  save_graphs: False
  save_graphs_path: "./graph"
  device_id: 0

# aicc
remote_save_url: "Please input obs url on AICC platform."

# runner
runner_config:
  epochs: 10
  batch_size: &batch_size 1
  sink_size: 2
  image_size: 224

# parallel
use_parallel: False
parallel:
  parallel_mode: 0 # 0-dataset, 1-semi, 2-auto, 3-hybrid
  gradients_mean: True
  search_mode: "sharding_propagation"
  enable_parallel_optimizer: False
  full_batch: False
parallel_config:
  data_parallel: 1
  model_parallel: 1
  pipeline_stage: 1
  micro_batch_num: 1
  vocab_emb_dp: True
  gradient_aggregation_group: 4
micro_batch_interleave_num: 1

# recompute
recompute_config:
  recompute: False
  parallel_optimizer_comm_recompute: False
  mp_comm_recompute: True
  recompute_slice_activation: False

# autotune
auto_tune: False
filepath_prefix: './autotune'
autotune_per_step: 10

# profile
profile: False
profile_start_step: 1
profile_stop_step: 10
init_start_profile: False
profile_communication: False
profile_memory: True

# Trainer
trainer:
  type: ImageToTextGenerationTrainer
  model_name: 'itt_blip2_stage2_vit_g_baichuan_7b'

# train dataset
eval_dataset:  &eval_dataset
  data_loader:
    type: Flickr8kDataLoader
    dataset_dir: "./checkpoint_download/Flickr8k"
    stage: "train"
    column_names: [ "image", "text"]
    hypothesis_template: "{}"
  transforms:
    - type: ToPIL
    - type: Resize
      size: 224
      interpolation: 'linear'
    - type: CenterCrop
      size: 224
    - type: ToTensor
    - type: Normalize
      mean: [0.48145466, 0.4578275, 0.40821073]
      std: [0.26862954, 0.26130258, 0.27577711]
      is_hwc: False
  num_parallel_workers: 8
  python_multiprocessing: False
  drop_remainder: False
  batch_size: 32
  repeat: 1
  numa_enable: False
  prefetch_size: 30
  seed: 2022

eval_dataset_task:
  type: ZeroShotImageClassificationDataset
  dataset_config: *eval_dataset
# model
model:
  model_config:
    type: Blip2Config
    batch_size: *batch_size
    freeze_vision: True
    freeze_text: True
    max_txt_len: 32
    checkpoint_name_or_path: ""
    dtype: "float32"
    compute_dtype: "float16"
    layernorm_dtype: "float32"
    softmax_dtype: "float32"
    vision_config:
      type: ViTConfig
      image_size: 224
      patch_size: 14
      num_channels: 3
      initializer_range: 0.001
      hidden_size: 1408
      num_hidden_layers: 39
      num_attention_heads: 16
      intermediate_size: 6144
      qkv_bias: true
      hidden_act: gelu
      post_layernorm_residual: false
      layer_norm_eps: 1.0e-6
      attention_probs_dropout_prob: 0.0
      hidden_dropout_prob: 0.0
      drop_path_rate: 0.0
      use_mean_pooling: false
      encoder_stride: 16
      checkpoint_name_or_path: "vit_g_p16"

    text_config:
      type: LlamaConfig
      seq_length: 64  # sum of max_txt_len and num_query_token
      hidden_size: 4096
      num_layers: 32
      num_heads: 32
      vocab_size: 64001
      multiple_of: 256
      rms_norm_eps: 1.0e-6
      bos_token_id: 1
      eos_token_id: 2
      pad_token_id: 0
      ignore_token_id: -100
      compute_dtype: "float16"
      layernorm_compute_type: "float32"
      softmax_compute_type: "float32"
      rotary_dtype: "float16"
      param_init_type: "float16"
      use_past: True
      offset: 0
      repetition_penalty: 1
      max_decode_length: 512
      top_k: 1
      top_p: 1
      do_sample: False
      checkpoint_name_or_path: ""
  arch:
    type: Blip2ImageToTextGeneration

# processor
processor:
  type: Blip2Processor
  image_processor:
    type: Blip2ImageProcessor
    image_size: 224  # input image size
  tokenizer:
    type: LlamaTokenizer
    pad_token: '<pad>'
    bos_token: '<s>'
    unk_token: '</s>'
    eos_token: '</s>'
    add_special_tokens: False
    padding: 'max_length'
    truncation: True
    max_length: 32
    vocab_file: ""


# callbacks
callbacks:
  - type: MFLossMonitor
  - type: CheckpointMointor
    prefix: "mindformers"
    save_checkpoint_steps: 10000
    integrated_save: True
    async_save: False
  - type: ObsMonitor
eval_callbacks:
  - type: ObsMonitor
